from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from datetime import datetime

class DeviceTokenRegisterRequest(BaseModel):
    token: str = Field(..., description="FCM Token string generated by Firebase SDK")
    device_type: Optional[str] = Field("web", description="Device type: 'web', 'android', 'ios'")

class DeviceTokenUnregisterRequest(BaseModel):
    token: str = Field(..., description="FCM Token string to deactivate")

class DeviceTokenResponse(BaseModel):
    id: int
    user_id: int
    token: str
    device_type: str
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True

class SendPushNotificationRequest(BaseModel):
    user_id: int = Field(..., description="User ID to receive the notification")
    title: str = Field(..., description="Notification Title")
    body: str = Field(..., description="Notification Message Body")
    data: Optional[Dict[str, str]] = Field(None, description="Optional payload key-value data")

class UserNotificationResponse(BaseModel):
    id: int
    user_id: int
    title: str
    message: str
    type: str
    is_read: bool
    link: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True

class UserNotificationListResponse(BaseModel):
    notifications: list[UserNotificationResponse]
    unread_count: int
