from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from datetime import datetime

class DeviceTokenRegisterRequest(BaseModel):
    token: str = Field(..., description="FCM Token string generated by Firebase SDK")
    device_type: Optional[str] = Field("web", description="Device type: 'web', 'android', 'ios'")

class DeviceTokenUnregisterRequest(BaseModel):
    token: str = Field(..., description="FCM Token string to deactivate")

class DeviceTokenResponse(BaseModel):
    id: int
    user_id: int
    token: str
    device_type: str
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True

class SendPushNotificationRequest(BaseModel):
    user_id: int = Field(..., description="User ID to receive the notification")
    title: str = Field(..., description="Notification Title")
    body: str = Field(..., description="Notification Message Body")
    data: Optional[Dict[str, str]] = Field(None, description="Optional payload key-value data")

class UserNotificationResponse(BaseModel):
    id: int
    user_id: int
    title: str
    message: str
    type: str
    is_read: bool
    link: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True

class UserNotificationListResponse(BaseModel):
    notifications: list[UserNotificationResponse]
    unread_count: int

class AdminBroadcastNotificationRequest(BaseModel):
    title: str = Field(..., description="Título del comunicado o actualización")
    message: str = Field(..., description="Contenido de la notificación")
    type: str = Field("sistema", description="'sistema', 'anuncio', 'mantenimiento', 'alerta'")
    target_audience: str = Field("all", description="'all', 'role', 'specific_users'")
    target_role_id: Optional[int] = Field(None, description="ID del rol si target_audience es 'role'")
    target_user_ids: Optional[list[int]] = Field(None, description="Lista de IDs de usuarios si target_audience es 'specific_users'")
    link: Optional[str] = Field(None, description="Enlace interno o externo opcional")
    send_push: bool = Field(True, description="Enviar también alerta Push via Firebase")

class AdminBroadcastLogResponse(BaseModel):
    id: int
    sender_id: Optional[int] = None
    sender_name: Optional[str] = None
    title: str
    message: str
    type: str
    target_audience: str
    target_role_name: Optional[str] = None
    recipients_count: int
    link: Optional[str] = None
    sent_push: bool
    created_at: datetime

    class Config:
        from_attributes = True

