"""Add granted_shares to packages

Revision ID: 176b81e08e3b
Revises: 10fc32217e70
Create Date: 2026-07-08 09:54:57.052419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176b81e08e3b'
down_revision: Union[str, Sequence[str], None] = '10fc32217e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('granted_shares', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'granted_shares')
    # ### end Alembic commands ###
