"""create withdrawals table

Revision ID: 7a2b9d8e5f12
Revises: f23b2c8a14b9
Create Date: 2026-07-13 17:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2b9d8e5f12'
down_revision: Union[str, None] = 'f23b2c8a14b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False, server_default='inversion'),
    sa.Column('tipo', sa.Enum('rendimiento', 'capital', 'bono', name='withdrawaltype'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
    sa.Column('monto_neto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'procesado', 'rechazado', 'cancelado', name='withdrawalstatus'), nullable=False, server_default='pendiente'),
    sa.Column('metodo_pago', sa.String(length=255), nullable=True),
    sa.Column('banco', sa.String(length=255), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=255), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('aprobado_por', sa.BigInteger(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('procesado_por', sa.BigInteger(), nullable=True),
    sa.Column('fecha_procesamiento', sa.DateTime(), nullable=True),
    sa.Column('comprobante_pago', sa.String(length=255), nullable=True),
    sa.Column('receipt_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procesado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    # ### end Alembic commands ###
