"""create contract accelerations

Revision ID: a1b2c3d4e5f6
Revises: f23b2c8a14b9
Create Date: 2026-07-14 15:46:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '7a2b9d8e5f12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contract_accelerations',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('investor_id', sa.BigInteger(), nullable=False),
        sa.Column('investment_request_id', sa.BigInteger(), nullable=False),
        sa.Column('contract_period_id', sa.Integer(), nullable=True),
        sa.Column('original_days', sa.Integer(), nullable=False),
        sa.Column('acceleration_percentage', sa.Numeric(precision=5, scale=2), server_default='5.00', nullable=False),
        sa.Column('days_to_reduce', sa.Numeric(precision=20, scale=6), server_default='0.000000', nullable=False),
        sa.Column('capital_released', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=True),
        sa.Column('new_duration', sa.Numeric(precision=20, scale=6), server_default='0.000000', nullable=False),
        sa.Column('applied', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('bonus_amount', sa.Numeric(precision=20, scale=6), server_default='0.000000', nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['contract_period_id'], ['periods.id'], name='fk_accelerations_period', ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['investment_request_id'], ['investment_requests.id'], name='fk_accelerations_request', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name='fk_accelerations_investor', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_accelerations')
    # ### end Alembic commands ###
