from fastapi import APIRouter
from src.api.v1.endpoints import roles, users, auth, periods, packages, investors, bank_accounts, wallets, investment_requests, withdrawals, investments, system_events, audit, sarlaft, commercial_sales, analytics, templates, beneficiaries, potential_referrals, chat, crm, crm_emails, notifications, tickets, investor_documents, uploads, banks, investment_ranks

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(roles.router, prefix="", tags=["security"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(periods.router, prefix="/periods", tags=["periods"])
api_router.include_router(packages.router, prefix="/packages", tags=["packages"])
api_router.include_router(investors.router, prefix="/investors", tags=["investors"])
api_router.include_router(banks.router, prefix="/banks", tags=["banks"])
api_router.include_router(bank_accounts.router, prefix="/bank-accounts", tags=["bank-accounts"])
api_router.include_router(wallets.router, prefix="/wallets", tags=["wallets"])
api_router.include_router(investments.router, prefix="/investments", tags=["investments"])
api_router.include_router(investment_requests.router, prefix="/investment-requests", tags=["investment-requests"])
api_router.include_router(withdrawals.router, prefix="/withdrawals", tags=["withdrawals"])
api_router.include_router(investment_ranks.router, prefix="", tags=["rankings"])

api_router.include_router(system_events.router, prefix="/admin-system-events", tags=["system-events"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(sarlaft.router, prefix="/sarlaft", tags=["sarlaft"])
api_router.include_router(commercial_sales.router, prefix="/commercial", tags=["commercial"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(templates.router, prefix="", tags=["templates"])
api_router.include_router(beneficiaries.router, prefix="", tags=["beneficiaries"])
api_router.include_router(potential_referrals.router, prefix="", tags=["potential-referrals"])
api_router.include_router(chat.router, prefix="", tags=["chat"])
api_router.include_router(crm.router, prefix="", tags=["crm"])
api_router.include_router(crm_emails.router, prefix="", tags=["crm-emails"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(tickets.router, prefix="/tickets", tags=["tickets"])
api_router.include_router(investor_documents.router, prefix="", tags=["investor-documents"])
api_router.include_router(uploads.router, prefix="/uploads", tags=["uploads"])
